packages:
# Global settings
  all:
    compiler:
    - gcc@11.4.0
    providers:
      mpi: [mpich@4.0]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
    variants: build_type=Release
# External packages from Ubuntu repos
  m4:
    buildable: false
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  gmake:
    buildable: false
    externals:
    - spec: gmake@4.3
      prefix: /usr
  automake:
    buildable: false
    externals:
    - spec: automake@1.16.5
      prefix: /usr
  autoconf:
    buildable: false
    externals:
    - spec: autoconf@2.71
      prefix: /usr
  libtool:
    buildable: false
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  git:
    buildable: false
    externals:
    - spec: git@2.34.1~tcltk
      prefix: /usr
  mpich:
    buildable: false
    externals:
    - spec: mpich@4.0+hydra device=ch4 netmod=ofi
      prefix: /usr
# Package preferences to be built by Spack for correct Exawind
  ascent:
    variants: ~fortran~openmp
  amr-wind:
    variants: +tiny_profile
  conduit:
    variants: ~fortran~hdf5_compat
  boost:
    version: [1.78.0]
    variants: cxxstd=17
  cmake:
    version: [3.26.3]
    variants: build_type=Release
  hdf5:
    version: [1.10.7]
    variants: +cxx+hl
  masa:
    variants: ~fortran~python
  netcdf-c:
    require: '@4.7.4'
    variants: +parallel-netcdf maxdims=65536 maxvars=524288
  openfast:
    version: [master]
    variants: +cxx
  parallel-netcdf:
    version: [1.12.2]
    variants: ~fortran
  perl:
    require: '@5.34.1'
  tioga:
    version: [develop]
  hypre:
    require: '@develop'
    variants: ~fortran
  hypre2:
    require: '@develop'
    variants: ~fortran
  yaml-cpp:
    version: [0.6.3]
